CATEGORIES = {
    "culture and arts" : {
        "Classics": "The study of the languages, literature, philosophy, and histories of ancient Greece and Rome.",
        "Critical Theory": "A philosophical approach to culture, literature, and arts that seeks to confront the social, historical, and ideological forces and structures that produce and constrain it.",
        "Cultural Anthropology": "The study of contemporary and historical human cultures and societies through their customs, practices, and social behaviors.",
        "Clothing": "Items worn on the body, typically made from textiles or fabrics, serving functional and cultural purposes.",
        "Folklore": "The traditional beliefs, customs, stories, songs, and practices of a culture, passed through generations by word of mouth.",
        "Food and Drink Culture": "The practices, attitudes, and norms associated with the consumption of food and beverages within a particular society.",
        "Language": "A system of communication used by a particular community or country, consisting of spoken, written, or signed words and the systems for their use.",
        "Literature": "Written works, especially those considered to have artistic or intellectual value.",
        "Museology": "The study of museums and their role in education, cultural preservation, and entertainment.",
        "Mythology": "A collection of myths, especially one belonging to a particular religious or cultural tradition.",
        "Philosophy": "The study of fundamental questions about existence, knowledge, values, reason, mind, and language.",
        "Popular Culture": "The set of practices, beliefs, and objects that are dominant or prevalent in a society at a given point in time.",
        "Science and Culture": "The interaction between scientific knowledge and cultural practices and their co-influence on each other.",
        "Traditions": "Long-established customs or beliefs that are passed down within a society.",
        "Arts and Crafts": "A broad domain of practice that involves the creation of artistic and functional objects.",
        "Celebrity": "A person who is widely recognized in the society, often through media, for their achievements or characteristics.",
        "Censorship in the Arts": "The regulation or suppression of what can be accessed, published, or viewed within the arts based on societal, cultural, or political standards.",
        "Festivals": "Events usually celebrated by a community, centering on some characteristic aspect of that community and its religion or cultures.",
        "Humor": "The quality of being amusing or comic, especially as expressed in literature or speech.",
        "Museums": "Institutions that collect, safeguard and make accessible artifacts and other objects of artistic, cultural, historical, or scientific importance.",
        "Parties": "Social gatherings of invited guests, typically involving eating, drinking, and entertainment.",
        "Poetry": "A form of literature that uses aesthetic and often rhythmic qualities of language to evoke meanings.",
        "Circuses": "A traveling company of performers that may include acrobats, clowns, trained animals, and other novelty acts.",
        "Dance": "The movement of the body in a rhythmic way, usually to music and within a given space, for the purpose of expressing an idea or emotion.",
        "Film": "A series of moving pictures that are projected onto a screen to create the illusion of motion.",
        "Music": "The art of arranging sounds in time to produce a composition through the elements of melody, harmony, rhythm, and timbre.",
        "Opera": "A dramatic work in one or more acts, set to music for singers and instrumentalists.",
        "Storytelling": "The social and cultural activity of sharing stories, sometimes with improvisation, theatrics, or embellishment.",
        "Theatre": "A branch of the performing arts that involves acting out stories in front of an audience using combinations of speech, gesture, music, dance, sound, and spectacle.",
        "Architecture": "The art and science of designing buildings and structures.",
        "Comics": "A medium used to express ideas via images, often combined with text or other visual information.",
        "Crafts": "Activities that involve skill in making things by hand.",
        "Design": "The creation of a plan or convention for the construction of an object, system, or measurable human interaction.",
        "Drawing": "The art or technique of producing images on a surface, usually paper, by means of marks, usually of ink, graphite, or chalk.",
        "Film Animation": "The process of creating moving images by displaying a rapid succession of static images that minimally differ from each other.",
        "New Media Art": "Art that involves digital technology as an essential part of the creative or presentation process.",
        "Painting": "The practice of applying paint, pigment, color, or other medium to a solid surface.",
        "Photography": "The art, application, and practice of creating durable images by recording light or other electromagnetic radiation.",
        "Sculpture": "The art of creating two- or three-dimensional representations, as by carving stone, casting metal, or modeling clay.",
        "Board Games": "Games that involve counters or pieces moved or placed on a pre-marked surface or 'board,' according to a set of rules.",
        "Card Games": "Games using playing cards as the primary device with which the game is played, be they traditional or game-specific.",
        "Dolls": "Model human figures, often used as children’s toys.",
        "Puppetry": "The art of manipulating inanimate objects that might appear to be living entities.",
        "Puzzles": "Games, toys, or problems designed to test ingenuity or knowledge.",
        "Role-playing Games": "Games in which players assume the roles of characters and collaborate to create narratives.",
        "Video Games": "Electronic games that involve interaction with a user interface to generate visual feedback on a device.",
        "Air Sports": "Sports such as skydiving, hang gliding, and balloon racing which are undertaken principally in the air.",
        "American Football": "A competitive team sport known for mixing strategies with physical play.",
        "Association Football": "Known as soccer in some countries, it's a sport where two teams of eleven players must maneuver a ball into the opposing team's goal without using their hands.",
        "Auto Racing": "Motorsport involving the racing of automobiles for competition.",
        "Baseball": "A bat-and-ball sport played between two teams who take turns batting and fielding.",
        "Basketball": "A team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court, compete with the primary objective of shooting a basketball through the defender's hoop.",
        "Boating": "The leisurely activity of travelling by boat, or the recreational use of a boat whether powerboats, sailboats, or man-powered vessels.",
        "Boxing": "A combat sport in which two people wearing protective gloves throw punches at each other for a predetermined set of time in a boxing ring.",
        "Canoeing": "A sport or recreational activity which involves paddling a canoe with a single-bladed paddle.",
        "Cricket": "A bat-and-ball game played between two teams of eleven players on a field at the center of which is a 22-yard pitch with a wicket at each end, each comprising two bails balanced on three stumps.",
        "Cycling": "The use of bicycles for transport, recreation, exercise, or sport.",
        "Exercise": "Activities undertaken to maintain or improve health and fitness.",
        "Fishing": "The activity of trying to catch fish, typically by using nets, fishing rods, or by other means.",
        "Golf": "A club-and-ball sport in which players use various clubs to hit balls into a series of holes on a course in as few strokes as possible.",
        "Gymnastics": "A sport involving the performance of exercises requiring balance, strength, flexibility, agility, coordination, and endurance.",
        "Hobbies": "Leisure activities that are pursued for pleasure and relaxation.",
        "Horse Racing": "The sport of running horses at speed, mainly Thoroughbreds with a rider astride or Standardbreds with the horse pulling a conveyance with a driver.",
        "Ice Hockey": "A contact team sport played on ice skates, usually in a rink, in which two teams of skaters use sticks to shoot a vulcanized rubber puck into their opponent's net to score points.",
        "Lacrosse": "A team sport played with a lacrosse stick and a lacrosse ball that is contested by two teams.",
        "Olympic Games": "Leading international sporting events featuring summer and winter sports competitions in which thousands of athletes from around the world participate in a variety of competitions.",
        "Rugby League": "A full-contact sport played by two teams of thirteen players on a rectangular field.",
        "Rugby Union": "A team sport which originated in England in the early 19th century. One of the two codes of rugby football, it is based on running with the ball in hand.",
        "Sailing": "The sport of using wind to power sails and propel a boat on water, ice, or land over a prescribed course.",
        "Skiing": "A means of transport using skis to glide on snow.",
        "Swimming": "The sport or activity of propelling oneself through water using the limbs.",
        "Tennis": "A racket sport that can be played individually against a single opponent or between two teams of two players each.",
        "Track and Field": "A sport which includes athletic contests established on the skills of running, jumping, and throwing.",
        "Walking Trails": "Paths or tracks that are primarily used for walking.",
        "Water Sports": "Sports played or performed in water.",
        "Whitewater Sports": "Sports involving the navigating of rivers or other bodies of water that have a high gradient and fast moving water."
},

"geography and places": {
    "Earth": "The third planet from the Sun, home to all known life and characterized by diverse geographies and ecosystems.",
    "World": "A term used to describe the entirety of Earth or the human sphere of activity and habitation.",
    "Bodies of water": "Any significant accumulation of water, generally on a planet's surface, including lakes, rivers, oceans, and ponds.",
    "Cities": "Large human settlements characterized by significant population, infrastructure, and cultural centers.",
    "Communities": "Groups of people living in the same place or having a particular characteristic in common.",
    "Continents": "Large landmasses on Earth's surface, distinctively larger than islands and encompassing multiple countries, except in the case of Australia.",
    "Countries": "Distinct territorial bodies within political geography, recognized as sovereign states.",
    "Deserts": "Arid regions with very little rainfall, making it hostile for plant and animal life.",
    "Lakes": "Large bodies of water surrounded by land on all sides, except for rivers or other outlets.",
    "Landforms": "Natural features of the Earth's surface, like mountains, plains, and plateaus.",
    "Mountains": "Large landforms that rise prominently above their surroundings, typically having a peak or ridges and a significant height above sea level.",
    "Navigation": "The process and activity of accurately ascertaining one's position and planning and following a route.",
    "Oceans": "Large bodies of salt water that cover most of Earth's surface, divided into the Atlantic, Pacific, Indian, Arctic, and Southern oceans.",
    "Populated places": "Areas where people live, such as towns, cities, or villages.",
    "Protected areas": "Regions designated for the protection and preservation of natural resources and biodiversity.",
    "Regions": "Areas broadly divided by physical characteristics (physical geography), human impact (human geography), or both.",
    "Rivers": "Large natural streams of water flowing along a channel to the sea, a lake, or another river.",
    "Subterranea": "Areas beneath the Earth’s surface, including caves and underground passages.",
    "Territories": "Defined areas owned and administered by a particular country, often not fully independent.",
    "Towns": "Populated areas larger than villages but smaller than cities.",
    "Villages": "Small clustered human settlements smaller than a town.",
    "Islands": "Land masses surrounded by water, smaller than continents and completely isolated by water.",
    "Peninsulas": "Pieces of land that are surrounded by water on three sides but connected to mainland.",
    "Forests": "Large areas dominated by trees and other plant life.",
    "Parks": "Protected areas, mainly for public enjoyment and recreation, often maintained by governmental entities.",
    "Natural Reserves": "Protected areas designated for the conservation of the natural environment.",
    "Valleys": "Low areas between hills or mountains, typically with a river or stream flowing through them.",
    "Glaciers": "Large, dense bodies of ice that move slowly over land, formed by the accumulation and compaction of snow.",
    "Seas": "Large bodies of saltwater, often connected to an ocean, but smaller and partially enclosed by land.",
    "Bays": "Broad inlets of the sea where the land curves inward, often providing calm waters.",
    "Capes": "High points of land that extend into a body of water.",
    "Plateaus": "Areas of flat, elevated land that rise sharply above the surrounding area on at least one side.",
    "Volcanoes": "Openings in Earth’s crust through which molten lava, ash, and gases from below the Earth's surface escape into the air.",
    "Archipelagos": "Groups or chains of islands clustered together in a large body of water.",
    "Canyons": "Deep gorges, typically with a river flowing through them, characterized by steep sides.",
    "Waterfalls": "Areas where water flows over a vertical drop or a series of steep drops in the course of a stream or river.",
    "Marshes": "Wetland areas typically flooded with water and dominated by herbaceous plants.",
    "Swamps": "Wetlands with more water than marshes and generally covered by woody plants.",
    "Reefs": "Ridges of jagged rock, coral, or sand just above or below the surface of the sea.",
    "Estuaries": "Partially enclosed coastal bodies of brackish water with one or more rivers or streams flowing into it and with a free connection to the open sea.",
    "Fjords": "Long, deep, narrow bodies of water that reach far inland, formed by glacial activity.",
    "Coastlines": "The areas where the land meets the sea or ocean, or the edge of a lake or river.",
    "Delta": "The area where a river divides before entering a larger body of water, typically rich in sediment.",
    "Highlands": "Areas of high or mountainous land.",
    "Lowlands": "Areas of lower land, often less than 200 meters above sea level, usually fertile and densely populated.",
    "Meadows": "Fields or grasslands, typically used for hay or serving as pasture.",
    "Plains": "Large areas of flat or gently undulating land.",
    "Prairies": "Large areas of natural grassland, primarily in the central parts of North America.",
    "Savannahs": "Mixed landscapes of open grasslands with scattered trees, found in tropical and subtropical regions.",
    "Tundra": "Cold, treeless regions found in the Arctic or on high mountains, where the soil is permanently frozen.",
    "Wetlands": "Areas where water covers the soil, or is present either at or near the surface of the soil all year or for varying periods of time.",
    "Atolls": "Ring-shaped coral reefs, islands, or series of islets that encircle a lagoon either partially or completely.",
    "Gulfs": "Large parts of the ocean that are enclosed by land, larger than bays.",
    "Strait": "Narrow passages of water connecting two larger bodies of water.",
    "Channel": "The physical confine of a river, slough or ocean strait consisting of a bed and banks.",
    "Lagoon": "Shallow body of water separated from a larger body of water by barrier islands or reefs.",
    "Moor": "Tracts of open uncultivated upland, typically covered with heather.",
    "Peaks": "The pointed tops of mountains.",
    "Ridges": "Long, narrow elevated land formations, typically having a crest.",
    "Sand Dunes": "Hills of loose sand built by the wind or the flow of water."
},



"human activities":{
    "Activism": "Efforts to promote, impede, direct, or intervene in social, political, economic, or environmental reform with the desire to make changes in society.",
    "Agriculture": "The science or practice of farming, including cultivation of the soil for the growing of crops and the rearing of animals to provide food, wool, and other products.",
    "Arts": "The expression or application of human creative skill and imagination, typically in visual form such as painting or sculpture, producing works to be appreciated primarily for their beauty or emotional power.",
    "Aviation": "The design, development, production, operation, and use of aircraft, especially heavier-than-air aircraft.",
    "Commemoration": "The action or ceremony of remembering and honoring people or events of the past.",
    "Communication": "The imparting or exchanging of information by speaking, writing, or using some other medium.",
    "Crime": "An action or omission that constitutes an offense that may be prosecuted by the state and is punishable by law.",
    "Design": "The art or process of deciding how something will look, work, etc., by drawing plans and making models.",
    "Education": "The process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs, and habits.",
    "Entertainment": "The action of providing or being provided with amusement or enjoyment.",
    "Fictional activities": "Engagements or actions within narrative works of fiction, imagined events or stories.",
    "Fishing": "The activity of catching fish, either for food or as a sport.",
    "Food and drink preparation": "The methods and techniques involved in assembling, cooking, and presenting food and beverages.",
    "Government": "The group of people with the authority to govern a country or state; a particular ministry in office.",
    "Hunting": "The activity of pursuing and killing wild animals for food or sport.",
    "Industry": "The economic activity concerned with the processing of raw materials and manufacture of goods in factories.",
    "Leisure activities": "Activities done for enjoyment when one is not working.",
    "Navigation": "The process or activity of accurately ascertaining one's position and planning and following a route.",
    "Observation": "The action or process of closely observing or monitoring something or someone.",
    "Performing arts": "Forms of creative activity that are performed in front of an audience, such as drama, music, and dance.",
    "Physical exercise": "Any bodily activity that enhances or maintains physical fitness and overall health and wellness.",
    "Planning": "The process of making plans for something.",
    "Politics": "The activities associated with the governance of a country or area, especially the debate between parties having power.",
    "Recreation": "Activity done for enjoyment when one is not working.",
    "Religion": "The belief in and worship of a superhuman controlling power, especially a personal God or gods.",
    "Human spaceflight": "The space travel with a crew or passengers aboard a spacecraft.",
    "Sports": "Activities involving physical exertion and skill in which an individual or team competes against another or others for entertainment.",
    "Trade": "The action of buying and selling goods and services.",
    "Transport": "The action of transporting someone or something or the process of being transported.",
    "Travel": "The action of traveling, typically abroad.",
    "Underwater human activities": "Activities conducted under the surface of water, involving professions like marine biology, underwater construction, or recreational activities such as scuba diving.",
    "Underwater diving": "The practice of descending below the water's surface to interact with the environment.",
    "War": "A state of armed conflict between different countries or different groups within a country.",
    "Work": "Activities involving mental or physical effort done in order to achieve a purpose or result.",
    "Human impact on the environment": "The changes to biophysical environments and ecosystems, biodiversity, and natural resources caused directly or indirectly by humans.",
    "Climate change": "A change in global or regional climate patterns, particularly a change apparent from the mid to late 20th century onwards and attributed largely to the increased levels of atmospheric carbon dioxide produced by the use of fossil fuels.",
    "Nature conservation": "The practice of protecting the natural environment on individual, organizational, or governmental levels, for the benefit of both the natural world and humans.",
    "Deforestation": "The clearing, clear-cutting or removal of a forest or stand of trees where the land is thereafter converted to a non-forest use.",
    "Environmentalism": "Concern about and action aimed at protecting the environment.",
    "Global warming": "The long-term heating of Earth’s climate system observed since the pre-industrial period due to human activities, primarily fossil fuel burning, which increases heat-trapping greenhouse gas levels in Earth's atmosphere.",
    "Pollution": "The presence in or introduction into the environment of a substance or thing that has harmful or poisonous effects.",
    "Human overpopulation": "Condition where the number of humans exceeds the carrying capacity of Earth.",
    "Urbanization": "The process of making an area more urban."
},


"mathematics and logic" : {
    "Mathematics": "The abstract science of number, quantity, and space, either as abstract concepts (pure mathematics) or as applied to other disciplines such as physics and engineering (applied mathematics).",
    "Mathematics Education": "The practice and study of teaching and learning mathematics, along with the associated scholarly research.",
    "Equations": "Mathematical statements that assert the equality of two expressions, typically involving variables and constants.",
    "Heuristics": "Simple, efficient rules intended to increase the probability of solving some problem, often as practical methods not guaranteed to be perfect or optimal.",
    "Measurement": "The process of obtaining the magnitude of a quantity relative to a unit of measurement.",
    "Numbers": "Mathematical objects used to count, measure, and label.",
    "Proofs": "Logical arguments that demonstrate the truth of a given assertion based on deductive reasoning.",
    "Theorems": "Statements that have been proven on the basis of previously established statements, such as other theorems, and generally accepted statements, such as axioms.",
    "Arithmetic": "The branch of mathematics dealing with the properties and manipulation of numbers, including operations such as addition, subtraction, multiplication, and division.",
    "Algebra": "A branch of mathematics that deals with symbols and the rules for manipulating these symbols; it is a unifying thread of almost all of mathematics.",
    "Geometry": "The branch of mathematics concerned with the properties and relations of points, lines, surfaces, and solids.",
    "Trigonometry": "A branch of mathematics that deals with the relationships between the sides and angles of triangles and the relevant functions of any angles.",
    "Mathematical Analysis": "A branch of mathematics that includes the theories of differentiation, integration, measure, limits, infinite series, and analytic functions.",
    "Calculus": "The mathematical study of continuous change, in the same way that geometry is the study of shape and algebra is the study of generalizations of arithmetic operations.",
    "Logic": "The systematic study of the form of valid inference, and more generally of logical form.",
    "Deductive Reasoning": "The process of reasoning from one or more statements (premises) to reach a logically certain conclusion.",
    "Inductive Reasoning": "A method of reasoning in which the premises are viewed as supplying strong evidence for the truth of the conclusion.",
    "History of Logic": "The study of the development of the science of valid inference (logic).",
    "Fallacies": "Mistaken beliefs based on unsound arguments; often used in the context of logical or factual errors in reasoning.",
    "Metalogic": "The study of the properties of logical systems and logics themselves, using mathematical methods akin to the study of metalanguages.",
    "Philosophy of Logic": "The study of the nature and scope of logic, examining the foundations of logic itself.",
    "Computational Science": "A field of study that uses advanced computing capabilities to understand and solve complex problems.",
    "Operations Research": "An analytical method of problem-solving and decision-making that is useful in the management of organizations.",
    "Theoretical Physics": "A branch of physics that employs mathematical models and abstractions of physical objects and systems to rationalize, explain, and predict natural phenomena.",
    "Statistics": "The study of the collection, analysis, interpretation, presentation, and organization of data.",
    "Analysis of Variance (ANOVA)": "A collection of statistical models used to analyze the differences among group means and their associated procedures.",
    "Bayesian Statistics": "A subset of statistics in which probability expresses a degree of belief in an event.",
    "Categorical Data": "Data that can be divided into specific groups or categories that do not have a natural order.",
    "Covariance and Correlation": "Measures of how much two random variables change together, where correlation is a normalized form of covariance.",
    "Data Analysis": "The process of systematically applying statistical and/or logical techniques to describe and illustrate, condense and recap, and evaluate data.",
    "Decision Theory": "The study of an agent's choices, particularly human behavior in the face of uncertainty.",
    "Design of Experiments": "The design of any task that aims to describe or explain the variation of information under conditions that are hypothesized to reflect the variation.",
    "Logic and Statistics": "The application of logical reasoning to statistical methods and conclusions.",
    "Multivariate Statistics": "Involves observation and analysis of more than one statistical outcome variable at a time.",
    "Non-parametric Statistics": "Statistical methods that are not based on parameterized families of probability distributions.",
    "Parametric Statistics": "Statistical methods that assume a particular form of data distribution (like a normal distribution) in the underlying population.",
    "Regression Analysis": "A set of statistical processes for estimating the relationships among variables.",
    "Sampling": "The process of selecting a subset of individuals from a statistical population to estimate characteristics of the whole population.",
    "Statistical Theory": "The theory or science of organizing and analyzing data, particularly the analysis of population characteristics by inference from sampling.",
    "Stochastic Processes": "Mathematical objects usually defined as collections of random variables, representing systems that evolve over time.",
    "Summary Statistics": "Used to summarize a set of observations, to communicate the largest amount of information as simply as possible.",
    "Survival Analysis": "A branch of statistics for analyzing the expected duration of time until one or more events happen, such as death in biological organisms and failure in mechanical systems.",
    "Time Series": "A series of data points indexed (or listed or graphed) in time order, typically used in statistics, signal processing, pattern recognition, econometrics, mathematical finance, weather forecasting, and earthquake prediction."
},

"natural and physical sciences" : {
    "Biology": "The scientific study of life and living organisms, including their structure, function, growth, origin, evolution, and distribution.",
    "Botany": "The branch of biology that deals with the study of plants, including their structure, properties, and biochemical processes.",
    "Ecology": "The branch of biology that studies the interactions among organisms and their biophysical environment, which includes both biotic and abiotic components.",
    "Health Sciences": "The branch of science focused on health, especially the study of medicine, nutrition, and other health-related issues.",
    "Medicine": "The science and practice of the diagnosis, treatment, and prevention of disease.",
    "Neuroscience": "The scientific study of the nervous system and its functions, disorders, and anatomy.",
    "Zoology": "The scientific study of the behavior, structure, physiology, classification, and distribution of animals.",
    "Earth Sciences": "All sciences related to the planet Earth, including geology, meteorology, and oceanography.",
    "Atmospheric Sciences": "The study of the Earth's atmosphere and its processes, including the weather and climate.",
    "Geography": "The study of places and the relationships between people and their environments.",
    "Geology": "The science that deals with the Earth's physical structure and substance, its history, and the processes that act on it.",
    "Geophysics": "The physics of the Earth and its environment in space; also the study of the Earth using quantitative physical methods.",
    "Oceanography": "The study of the physical and biological aspects of the ocean.",
    "Nature": "The phenomena of the physical world collectively, including plants, animals, the landscape, and other features and products of the earth, as opposed to humans or human creations.",
    "Animals": "Multicellular eukaryotic organisms that form the biological kingdom Animalia, characterized by their ability to move voluntarily, consume organic material, breathe oxygen, and reproduce sexually.",
    "Environment": "The surroundings or conditions in which a person, animal, or plant lives or operates.",
    "Humans": "Homo sapiens, the species of bipedal primates to which modern humans belong, characterized by a brain capable of complex thought.",
    "Life": "The condition that distinguishes animals and plants from inorganic matter, including the capacity for growth, reproduction, functional activity, and continual change preceding death.",
    "Natural Resources": "Resources occurring in nature that can be used to create wealth or for consumption, such as timber, water, and minerals.",
    "Plants": "Multicellular organisms in the kingdom Plantae that use photosynthesis to make their own food.",
    "Pollution": "The introduction of contaminants into the natural environment that cause adverse change.",
    "Physical Sciences": "Branches of science that study non-living systems, in contrast to the life sciences.",
    "Astronomy": "The branch of science that studies the universe beyond Earth, including the positions, motions, and properties of celestial objects.",
    "Chemistry": "The science of matter and the changes it undergoes during chemical reactions.",
    "Climate": "The weather conditions prevailing in an area in general or over a long period.",
    "Physics": "The natural science that studies matter, its motion and behavior through space and time, and the related entities of energy and force.",
    "Space": "The vast, seemingly empty expanse that exists beyond the Earth's atmosphere, in which celestial bodies are situated.",
    "Universe": "All existing matter and space considered as a whole; the cosmos. The universe is believed to be at least 10 billion light years in diameter and contains a vast number of galaxies; it has been expanding since its creation in the Big Bang about 13 billion years ago.",
    "Scientific Method": "A method of procedure that has characterized natural science since the 17th century, consisting in systematic observation, measurement, and experiment, and the formulation, testing, and modification of hypotheses.",
    "Scientists": "Individuals who conduct scientific research to advance knowledge in an area of interest."
},


"people and self" : {
    "People": "Humans considered collectively.",
    "Beginners and Newcomers": "Individuals who are new to a particular field or activity.",
    "Children": "Young human beings below the age of puberty or below the legal age of majority.",
    "Heads of State": "The chief public representatives of a country, such as a president or monarch.",
    "Humans": "Members of the species Homo sapiens, characterized by their ability to think critically and communicate complex ideas.",
    "People by Legal Status": "Groups categorized based on their legal rights and responsibilities.",
    "Men": "Adult human males.",
    "Old Age": "A later stage in life, typically characterized as the time after retirement from active work.",
    "Political People": "Individuals involved in politics, whether as elected officials, campaigners, or theorists.",
    "Rivalry": "Competition for the same objective or for superiority in the same field.",
    "Social Groups": "Collections of people who interact and share similar characteristics and a sense of unity.",
    "Subcultures": "Cultural groups within a larger culture, often with beliefs or interests at variance with those of the larger culture.",
    "Women": "Adult human females.",
    "People by City": "Categorization of individuals based on the city they are associated with.",
    "People by Company": "Groups defined by the company or corporation they work for or are associated with.",
    "People by Continent": "Classification of individuals based on the continent where they live or originate.",
    "People by Educational Institution": "Groups of individuals associated with specific schools, colleges, or universities.",
    "People by Ethnicity": "Classification based on shared cultural, linguistic, or ancestral traits.",
    "People by Descent": "Categorization based on ancestry or heritage.",
    "People by Medical or Psychological Condition": "Groups defined by specific health conditions they experience.",
    "People by Nationality": "Classification of individuals based on their country of citizenship.",
    "People by Occupation": "Categorization based on profession or job role.",
    "People by Political Orientation": "Groups defined by their political beliefs or affiliations.",
    "People by Religion": "Classification based on religious beliefs or affiliations.",
    "People by Revolution": "Individuals known for their involvement in revolutionary activities.",
    "People by Status": "Categorization based on social, economic, or other status.",
    "People by Year Born": "Groups classified by the year of their birth.",
    "People by Year Deceased": "Groups classified by the year they died.",
    "Lists of People": "Compiled lists of individuals often categorized by specific criteria.",
    "Personal Timelines": "Chronological lists or descriptions of significant events in an individual's life.",
    "Terms for Men": "Words or expressions specifically used to refer to men.",
    "Activists": "People who advocate for social change.",
    "Actors": "Individuals who perform in stage, film, or television productions.",
    "Astronauts": "People trained to command, pilot, or serve as crew members of spacecraft.",
    "Billionaires": "Individuals whose wealth exceeds one billion units of a given currency.",
    "Chief Executive Officers": "The highest-ranking corporate officers or administrators in charge of total management of an organization.",
    "Composers": "People who write music.",
    "Cyborgs": "Beings with both organic and biomechatronic body parts.",
    "Defectors": "Individuals who renounce allegiance to one state in favor of another.",
    "Generals": "High-ranking officers in the military.",
    "Inventors": "People who create something new or devise novel solutions.",
    "LGBT People": "Individuals identifying as lesbian, gay, bisexual, or transgender.",
    "Monarchs": "Kings, queens, or their equivalents who act as the head of state under a constitutional monarchy or sovereign state.",
    "Musicians": "People who play musical instruments or are musically talented.",
    "Musical Groups": "Bands or ensembles consisting of musicians.",
    "Philanthropists": "Individuals who seek to promote the welfare of others, especially by the generous donation of money to good causes.",
    "Philosophers": "Thinkers or writers who are considered knowledgeable in philosophy.",
    "Photographers": "People who take photographs, either as a hobby or profession.",
    "Politicians": "Individuals actively engaged in politics, particularly holding or seeking office in government.",
    "Presidents": "Heads of state or heads of government in countries where the president is the executive authority.",
    "Princes": "Male royalty, the sons or grandsons of a king or queen.",
    "Princesses": "Female royalty, the daughters or granddaughters of a king or queen.",
    "Revolutionaries": "People who work to overthrow established systems or governments.",
    "Scientists": "Individuals engaging in systematic activities to acquire knowledge that covers general truths or the operations of fundamental laws.",
    "Settlers": "People who move to a new area to establish a community.",
    "Singers": "People who sing, either professionally or as a hobby.",
    "Slaves": "People who are legally owned by someone else and forced to obey them.",
    "Victims": "Individuals who have been harmed, injured, or killed as a result of a crime, accident, or other event or action.",
    "People Associated with War": "Individuals known for their involvement in warfare, whether as soldiers, strategists, or civilians.",
    "Writers": "People who engage in writing books, articles, or any literary piece.",
    "Self": "A person's essential being that distinguishes them from others, especially considered as the object of introspection or reflexive action.",
    "Alter Egos": "Secondary or alternative personalities of individuals.",
    "Consciousness": "The state of being aware of and able to think and feel; the awareness or perception of something by a person.",
    "Gender": "The state of being male or female, typically used with reference to social and cultural differences rather than biological ones.",
    "Personality": "The combination of characteristics or qualities that form an individual's distinctive character.",
    "Sexuality": "Capacity for sexual feelings; a person's sexual orientation or preference.",
    "Sexual Orientation": "A person's pattern of emotional, romantic, or sexual attraction to others.",
    "Personal Life": "The course of an individual's life, especially when viewed as the sum of personal choices contributing to one's personal identity.",
    "Clothing": "Items worn to cover the body.",
    "Employment": "The condition of having paid work.",
    "Entertainment": "Activities that give pleasure or diversion to people such as music, films, and games.",
    "Food and Drink": "Substances consumed to provide nutritional support and pleasure.",
    "Games": "Structured forms of play, usually undertaken for enjoyment and sometimes used as educational tools.",
    "Health": "The state of being free from illness or injury.",
    "Hobbies": "Leisure activities done regularly in one's leisure time for pleasure.",
    "Home": "The place where one lives permanently, especially as a member of a family or household.",
    "Income": "Money received, especially on a regular basis, for work or through investments.",
    "Interpersonal Relationships": "The strong, deep, or close associations or acquaintances between two or more people that may range in duration from brief to enduring.",
    "Leisure": "Free time.",
    "Love": "An intense feeling of deep affection.",
    "Motivation": "The reason one has for acting or behaving in a particular way.",
    "Personal Development": "Activities that improve awareness and identity, develop talents and potential, build human capital and facilitate employability, enhance the quality of life and contribute to the realization of dreams and aspirations.",
    "Pets": "Domestic or tamed animals kept for companionship or pleasure."
},

"philosophy and thinking":{
    "Philosophy": "The study of the fundamental nature of knowledge, reality, and existence, especially when considered as an academic discipline.",
    "Branches": "The various subdivisions of philosophy that focus on specific aspects of reality and existence, such as ethics, logic, and metaphysics.",
    "Schools and Traditions": "Different groups or movements within philosophy that share common philosophic views or methods.",
    "Concepts": "The building blocks of thoughts and ideas in philosophy, representing fundamental categories of understanding.",
    "Theories": "Systematic ideational structures of principles that intend to explain aspects of reality and are based on philosophical concepts.",
    "Arguments": "Reasoned and structured exchanges of logic aimed at demonstrating the truth or falsehood of a proposition.",
    "Philosophers": "Thinkers who engage in rational inquiry into philosophical topics and contribute to philosophical knowledge.",
    "Literature": "Written works that are considered to be an art form, especially prose fiction, drama, and poetry in relation to philosophical topics.",
    "History": "The study of past events, particularly in human affairs as they relate to philosophical ideas and contexts.",
    "By period": "The organization of philosophical thought or history according to significant periods or eras.",
    "By region": "The study of philosophy divided by geographical regions which influence different philosophical traditions and ideas.",
    "Aesthetics": "The branch of philosophy that deals with the nature of beauty, art, and taste, and with the creation and appreciation of beauty.",
    "Epistemology": "The branch of philosophy concerned with the theory of knowledge, especially regarding its methods, validity, and scope.",
    "Ethics": "The branch of philosophy that involves systematizing, defending, and recommending concepts of right and wrong behavior.",
    "Logic": "The branch of philosophy that studies the principles of correct reasoning.",
    "Metaphysics": "The branch of philosophy that studies the first principles of being and reality, including questions about existence and the nature of objects.",
    "Social Philosophy": "A branch of philosophy that studies questions about society and its institutions, including the relationships among individuals within those institutions.",
    "Thinking": "The process of using one’s mind to consider or reason about something.",
    "Thinking skills": "The mental activities you use to process information, make connections, make decisions, and create new ideas.",
    "Attention": "The behavioral and cognitive process of selectively concentrating on a discrete aspect of information, whether deemed subjective or objective, while ignoring other perceivable information.",
    "Cognition": "The mental action or process of acquiring knowledge and understanding through thought, experience, and the senses.",
    "Cognitive biases": "Systematic patterns of deviation from norm or rationality in judgment, whereby inferences about other people and situations may be drawn in an illogical fashion.",
    "Creativity": "The use of imagination or original ideas to create something; inventiveness.",
    "Decision theory": "The study of an agent's choices, particularly human behavior in the face of uncertainty in economics, health, marketing, politics, and sports.",
    "Emotion": "Complex psychological states that involve three distinct components: a subjective experience, a physiological response, and a behavioral or expressive response.",
    "Error": "The state or condition of being wrong in conduct or judgment.",
    "Imagination": "The faculty or action of forming new ideas, or images or concepts of external objects not present to the senses.",
    "Intelligence researchers": "Scholars who study or explore the nature, origins, and practical implications of intelligence.",
    "Learning": "The process of acquiring new understanding, knowledge, behaviors, skills, values, attitudes, and preferences.",
    "Memory": "The faculty by which the mind stores and remembers information.",
    "Biases": "Prejudices in favor of or against one thing, person, or group compared with another, usually in a way considered to be unfair.",
    "Mnemonics": "Memory aids, especially those techniques that use vivid imagery and organizational devices.",
    "Nootropics": "Substances that claim to improve cognitive function, particularly executive functions, memory, creativity, or motivation, in healthy individuals.",
    "Organizational thinking": "Thinking processes associated with the planning, management, and execution of business activities within organizations.",
    "Perception": "The organization, identification, and interpretation of sensory information in order to represent and understand the presented information or environment.",
    "Problem solving": "The process of finding solutions to difficult or complex issues.",
    "Psychological adjustment": "The psychological processes through which people manage or cope with the demands and challenges of everyday life.",
    "Psychometrics": "The science of measuring mental capacities and processes."
},

"religion and belief systems":{
    "Allah": "The Arabic word for God in Islam.",
    "Bible": "The sacred scriptures of Christianity, consisting of the Old Testament and the New Testament.",
    "Buddhas": "In Buddhism, individuals who have attained full enlightenment and transcended desire and suffering.",
    "Deities": "Supernatural beings considered divine or sacred, worshipped or revered as creators and rulers of the universe.",
    "Demons": "Supernatural beings typically considered to be malevolent spirits.",
    "Exorcism": "The religious or spiritual practice of evicting demons or other spiritual entities from a person or an area they are believed to have possessed.",
    "God": "The supreme being in monotheistic faiths, creator and ruler of the universe.",
    "Jesus": "The central figure of Christianity, believed to be the son of God and savior of humanity.",
    "Mythology": "A collection of myths, especially one belonging to a particular religious or cultural tradition.",
    "Occult": "Knowledge of the hidden or paranormal, as opposed to facts and the manifest.",
    "Prayer": "A solemn request for help or expression of thanks addressed to God or another deity.",
    "Prophecy": "A message that is claimed by a prophet to have been communicated to them by a deity.",
    "Quran": "The holy book of Islam, believed to be the word of God as dictated to Muhammad.",
    "Religious ethics": "Moral principles that guide religions and influence the behavior of adherents.",
    "Religious law": "Legal systems derived from texts or traditions within a faith, such as Islamic Sharia or Jewish Halakha.",
    "Ritual": "A set of actions performed mainly for their symbolic value, which is prescribed by a religion or by the traditions of a community.",
    "Spirituality": "A broad concept with room for many perspectives, typically involving a search for meaning in life.",
    "Theology": "The study of the nature of God and religious belief.",
    "Religious faiths": "Systems of religious belief, which usually include a deity, narrative, rituals, and a moral code.",
    "Traditions": "Beliefs or behaviors passed down within a group or society with symbolic meaning or special significance.",
    "Movements": "Groups or collective activities that promote, reform, or help define the practices of a particular religion or belief system.",
    "Agnosticism": "The view that the existence of God, the divine, or the supernatural is unknown or unknowable.",
    "Animism": "The religious belief that objects, places, and creatures all possess a distinct spiritual essence.",
    "Atheism": "The absence of belief in the existence of deities.",
    "Deism": "The belief that a supreme being created the universe and that what governs natural law does not intervene in the universe.",
    "Determinism": "The philosophical belief that all events, including moral choices, are determined completely by previously existing causes.",
    "Esotericism": "The study of hidden meanings or mysteries typically accessible only to the initiated.",
    "Gnosticism": "A collection of ancient religious ideas and systems which assert that followers have direct access to God or the divine mystery.",
    "Humanism": "A philosophical stance that emphasizes the value and agency of human beings, individually and collectively.",
    "Monism": "The philosophical view that attributes oneness or singleness to a concept (e.g., existence).",
    "Monotheism": "The belief in the existence of only one God that created the world, a central element of religions including Judaism, Christianity, and Islam.",
    "Mysticism": "The practice of religious ecstasies (religious experiences during alternate states of consciousness), together with whatever ideologies, ethics, rites, myths, legends, and magic may be related to them.",
    "New Age": "A broad movement characterized by alternative approaches to traditional Western culture, with an interest in spirituality, mysticism, holism, and environmentalism.",
    "Paganism": "A religion other than one of the main world religions, specifically a non-Christian or pre-Christian religion.",
    "Pantheism": "The belief that reality is identical with divinity, or that all-things compose an all-encompassing, immanent god.",
    "Polytheism": "The worship of or belief in multiple deities usually assembled into a pantheon of gods and goddesses, along with their own religions and rituals.",
    "Shamanism": "Practice that involves a practitioner reaching altered states of consciousness in order to perceive and interact with a spirit world.",
    "Skepticism": "An attitude of doubt or a disposition to incredulity either in general or toward a particular object.",
    "Spiritualism": "A religious movement based on the belief that the spirits of the dead exist and have both the ability and the inclination to communicate with the living.",
    "Theosophy": "A collection of mystical and occultist philosophies concerning, or seeking direct knowledge of, the underlying workings of the universe.",
    "Transcendentalism": "A philosophical movement that developed in the late 1820s and 1830s in the eastern United States as a protest against the general state of intellectualism and spirituality.",
    "Unitarianism": "A Christian theological movement named for its belief that the God in Christianity is one entity, as opposed to the Trinity.",
    "Ayyavazhi": "A monotheistic Tamil belief system that originated in South India in the 19th century.",
    "Bahá'í Faith": "A religion teaching the essential worth of all religions, and the unity of all people, established in the 19th century.",
    "Buddhism": "A non-theistic religion or philosophy that encompasses a variety of traditions, beliefs, and spiritual practices largely based on teachings attributed to Buddha.",
    "Caodaism": "A monotheistic religion officially established in the city of Tây Ninh, southern Vietnam in 1926.",
    "Chinese folk religion": "Traditional religious practices in China including veneration of the ancestors, various deities, and the practice of Chinese astrology, among others.",
    "Christianity": "An Abrahamic monotheistic religion based on the life and teachings of Jesus Christ.",
    "Confucianism": "A philosophy or way of life propagated by Confucius in the 5th–6th century BC and followed by the Chinese people for more than two millennia.",
    "Druidry": "A modern spiritual or religious movement that promotes harmony and worship of nature, and respects the ancestors.",
    "Falun Gong": "A Chinese religious spiritual practice that combines meditation and qigong exercises with a moral philosophy.",
    "Hinduism": "The predominant religion of the Indian subcontinent, involving devotion to a number of gods and goddesses including rituals and observances.",
    "Islam": "An Abrahamic monotheistic religion teaching that there is only one God and that Muhammad is a messenger of God.",
    "Jainism": "An ancient Indian religion that prescribes a path of non-violence towards all living beings.",
    "Judaism": "The monotheistic religion of the Jews, tracing its origins to Abraham and having its spiritual and ethical principles embodied chiefly in the Torah and the Talmud.",
    "Modern paganism": "Contemporary religious movements influenced by or claiming to be derived from the various historical pagan beliefs of pre-modern peoples.",
    "Mormonism": "A religious and cultural tradition that originated from the revelations of Joseph Smith.",
    "Neo-druidism": "A form of modern spirituality or religion that generally promotes harmony and worship of nature, and respect for all beings.",
    "Rastafarianism": "A religion that originated in Jamaica in the 1930s and emphasizes the spiritual use of cannabis and the rejection of Western society.",
    "Satanism": "A group of ideological and philosophical beliefs based on the character of Satan.",
    "Scientology": "A set of religious beliefs and practices launched in May 1952 by American author L. Ron Hubbard.",
    "Shinto": "The traditional religion of Japan that focuses on ritual practices to be carried out diligently to establish a connection between present-day Japan and its ancient past.",
    "Sikhism": "A monotheistic religion that originated in the Punjab region of the Indian subcontinent around the end of the 15th century.",
    "Spiritism": "A spiritualistic philosophy and religious movement started in the 19th century by Allan Kardec, noted for its belief in the continual existence and spirits' ability to communicate with the living.",
    "Taoism": "A religious or philosophical tradition of Chinese origin which emphasizes living in harmony with the Tao.",
    "Tenrikyo": "A Japanese religion founded in the 19th century that emphasizes joyful living and relief from suffering.",
    "Unitarian Universalism": "A liberal religion characterized by a 'free and responsible search for truth and meaning'.",
    "Wicca": "A modern pagan, witchcraft religion that was developed in England during the first half of the 20th century.",
    "Zoroastrianism": "One of the world's oldest continuously practiced religions based on the teachings of the Iranian-speaking prophet Zoroaster.",
    "Buddhist Mythology": "The body of myths associated with Buddhism.",
    "Christian Mythology": "The body of myths associated with Christianity.",
    "Hindu Mythology": "The large body of myths related to Hinduism, ever since the Vedic times.",
    "Islamic Mythology": "The body of myths that supports the Islamic faith.",
    "Jewish Mythology": "The collection of traditional narratives that help explain and symbolize the Jewish religion.",
    "Criticism of Religion": "The critical examination of religious beliefs, texts, institutions, and practices."
},


"society and social sciences" : {
    "Activism": "Efforts to promote, impede, or direct social, political, economic, or environmental change or stasis.",
    "Business": "The practice of making one's living by engaging in commerce.",
    "Communication": "The act of conveying meanings from one entity or group to another through the use of mutually understood signs, symbols, and semiotic rules.",
    "Crime": "An unlawful act punishable by a state or other authority.",
    "Education": "The process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs, and habits.",
    "Ethnic Groups": "A category of people who identify with each other, usually on the basis of a presumed common genealogy or ancestry.",
    "Family": "A group of one or more parents and their children living together as a unit.",
    "Finance": "The management of large amounts of money, especially by governments or large companies.",
    "Globalization": "The process by which businesses or other organizations develop international influence or start operating on an international scale.",
    "Government": "The governing body of a nation, state, or community.",
    "Health": "The state of being free from illness or injury.",
    "Home": "The place where one lives permanently, especially as a member of a family or household.",
    "Industries": "Economic activities concerned with the processing of raw materials and manufacture of goods in factories.",
    "Infrastructure": "The basic physical and organizational structures and facilities needed for the operation of a society or enterprise.",
    "Law": "The system of rules which a particular country or community recognizes as regulating the actions of its members and which it may enforce by the imposition of penalties.",
    "Mass Media": "The media technologies that are intended to reach a large audience by mass communication.",
    "Military": "The armed forces of a country.",
    "Money": "A current medium of exchange in the form of coins and banknotes; coins and banknotes collectively.",
    "Organizations": "An organized group of people with a particular purpose, such as a business or government department.",
    "Peace": "Freedom from disturbance; tranquility; a state or period in which there is no war or a war has ended.",
    "Politics": "The activities associated with the governance of a country or area, especially the debate between parties having power.",
    "Real Estate": "Property consisting of land and the buildings on it, along with its natural resources.",
    "Rights": "Legal, social, or ethical principles of freedom or entitlement; that is, rights are the fundamental normative rules about what is allowed of people or owed to people.",
    "War": "A state of armed conflict between different countries or different groups within a country.",
    "Anthropology": "The study of humans, early hominids and primates, such as chimpanzees.",
    "Archaeology": "The study of human activity through the recovery and analysis of material culture.",
    "Cultural Studies": "An interdisciplinary field of research that examines the political dynamics of contemporary culture and its historical foundations.",
    "Demographics": "Statistical data relating to the population and particular groups within it.",
    "Economics": "The branch of knowledge concerned with the production, consumption, and transfer of wealth.",
    "Information Science": "The study of the collection, classification, manipulation, storage, retrieval, and dissemination of information.",
    "International Relations": "The study of the interactions between nations, including the roles of states, intergovernmental organizations, non-governmental organizations, and multinational corporations.",
    "Linguistics": "The scientific study of language and its structure.",
    "Media Studies": "The study of mass media, especially journalism and broadcasting.",
    "Political Science": "The branch of knowledge that deals with systems of government and the analysis of political activity and behavior.",
    "Psychology": "The scientific study of the human mind and its functions, especially those affecting behavior in a given context.",
    "Public Administration": "The implementation of government policy and an academic discipline that studies this implementation and prepares civil servants for working in the public service.",
    "Sexology": "The scientific study of human sexuality, including human sexual interests, behaviors, and functions.",
    "Social Scientists": "Researchers specialized in disciplines that examine the social life of human groups and individuals.",
    "Sociology": "The study of the development, structure, and functioning of human society.",
    "Social Work": "A profession concerned with helping individuals, families, groups, and communities to enhance their individual and collective well-being.",
    "Systems Theory": "An interdisciplinary study of systems in general, to elucidate principles that can be applied to all types of systems in all fields of research."
},


"technology and applied sciences":{
    "Agriculture": "The science, art, and practice of cultivating soil, growing crops, and raising livestock.",
    "Agronomy": "The science of soil management and crop production.",
    "Architecture": "The art and science of designing and constructing buildings and other physical structures.",
    "Automation": "The use of various control systems for operating equipment such as machinery, processes in factories, boilers, and heat treating ovens with minimal or reduced human intervention.",
    "Biotechnology": "The use of living systems and organisms to develop or make products, or any technological application that uses biological systems, living organisms, or derivatives thereof, to make or modify products or processes for specific use.",
    "Cartography": "The study and practice of making maps.",
    "Chemical Engineering": "The branch of engineering that deals with the conversion of chemicals into useful products.",
    "Communication Media Studies": "The study of how people communicate with one another using different mediums.",
    "Telecommunications": "The transmission of information over significant distances to communicate.",
    "Construction": "The process of constructing a building or infrastructure.",
    "Control Theory": "An interdisciplinary branch of engineering and mathematics that deals with the behavior of dynamical systems with inputs.",
    "Design": "The creation of a plan or convention for the construction of an object, system, or measurable human interaction.",
    "Digital Divide": "The gap between demographics and regions that have access to modern information and communications technology, and those that don't or have restricted access.",
    "Earthquake Engineering": "The scientific field concerned with protecting society, the natural and the man-made environment from earthquakes by limiting the seismic risk to socio-economically acceptable levels.",
    "Energy": "The quantitative property that must be transferred to an object in order to perform work on, or to heat, the object.",
    "Ergonomics": "The study of people's efficiency in their working environment.",
    "Firefighting": "The act of attempting to prevent the spread of and extinguish significant unwanted fires in buildings, vehicles, woodlands, etc.",
    "Fire Prevention": "The process of reducing the source of ignition and substances that fuel a fire in order to lower the risk of fire.",
    "Forensic Science": "The application of science to criminal and civil laws, mainly—on the criminal side—during criminal investigation, as governed by the legal standards of admissible evidence and criminal procedure.",
    "Forestry": "The science and craft of creating, managing, using, conserving, and repairing forests, woodlands, and associated resources for human and environmental benefits.",
    "Industry": "The production of goods or related services within an economy.",
    "Information Science": "The study of the collection, classification, manipulation, storage, retrieval, and dissemination of information.",
    "Internet": "The global system of interconnected computer networks that use the Internet protocol suite (TCP/IP) to communicate between networks and devices.",
    "Management": "The administration of an organization, whether it is a business, a not-for-profit organization, or government body.",
    "Manufacturing": "The production of merchandise for use or sale using labor and machines, tools, chemical and biological processing, or formulation.",
    "Marketing": "The study and management of exchange relationships, including the activities of setting a marketing strategy for an organization and its implementation through advertising and promotion.",
    "Medicine": "The science and practice of the diagnosis, treatment, and prevention of disease.",
    "Unsolved Problems in Neuroscience": "The ongoing research challenges and questions in the field of neuroscience.",
    "Metalworking": "The process of working with metals to create individual parts, assemblies, or large-scale structures.",
    "Microtechnology": "Technology with features near one micrometre (one millionth of a meter, or 1 µm).",
    "Military Science": "The study of the technique, psychology, practice, and other phenomena which constitute war and armed conflict.",
    "Mining": "The extraction of valuable minerals or other geological materials from the Earth.",
    "Nanotechnology": "The manipulation of matter on an atomic, molecular, and supramolecular scale.",
    "Nuclear Technology": "Technology that involves the nuclear reactions of atomic nuclei.",
    "Optics": "The branch of physics that involves the behavior and properties of light, including its interactions with matter and the construction of instruments that use or detect it.",
    "Plumbing": "The system of pipes, drains, fittings, valves, valve assemblies, and devices installed in a building for the distribution of water for drinking, heating and washing, and the removal of waterborne wastes.",
    "Robotics": "The branch of technology that deals with the design, construction, operation, and application of robots.",
    "Sound Technology": "The engineering discipline that focuses on sound, acoustics, and the application of sound through technology.",
    "Technology Forecasting": "The prediction of future characteristics of useful technological machines, procedures, or techniques.",
    "Tools": "Devices that carry out a particular function, typically used to facilitate complex or labor-intensive tasks.",
    "Apps": "Applications, especially as downloaded by a user to a mobile device.",
    "Artificial Intelligence": "The simulation of human intelligence processes by machines, especially computer systems.",
    "Classes of Computers": "Categories based on size, power, and performance from small personal digital assistants to supercomputers.",
    "Companies": "Businesses or corporations engaged in commercial, industrial, or professional activities.",
    "Computer Architecture": "The set of rules and methods that describe the functionality, organization, and implementation of computer systems.",
    "Computer Model": "A computer program that attempts to simulate an abstract model of a particular system.",
    "Computer Engineering": "The discipline that integrates several fields of electrical engineering and computer science required to develop computer hardware and software.",
    "Computer Science": "The study of algorithmic processes and computational machines.",
    "Computer Security": "The protection of computer systems from theft or damage to their hardware, software, or electronic data, as well as from disruption or misdirection of the services they provide.",
    "Computing and Society": "The study of the interaction between people (society) and computers.",
    "Data": "Facts and statistics collected together for reference or analysis.",
    "Embedded Systems": "A computer system with a dedicated function within a larger mechanical or electrical system, often with real-time computing constraints.",
    "Free Software": "Software that gives users the freedom to use, study, distribute, and modify it.",
    "Human–Computer Interaction": "The study and planned design of human and computer activities.",
    "Information Systems": "Organized systems for the collection, organization, storage, and communication of information.",
    "Information Technology": "The use of systems (especially computers and telecommunications) for storing, retrieving, and sending information.",
    "Internet": "The global system of interconnected computer networks that use the Internet protocol suite (TCP/IP) to communicate between networks and devices.",
    "Mobile Web": "The use of internet-connected applications, or browser-based access to the Internet from a handheld mobile device, such as a smartphone or a tablet computer.",
    "Languages": "Systems of symbols and rules for writing programs or algorithms.",
    "Multimedia": "The use of different content forms such as text, audio, images, animations, video, and interactive content.",
    "Networks (Industrial)": "Large scale networks designed to support industrial processes.",
    "Operating Systems": "Software that manages computer hardware, software resources, and provides common services for computer programs.",
    "Platforms": "The underlying computer system on which application programs can run.",
    "Product Lifecycle Management": "The process of managing the entire lifecycle of a product from inception, through engineering design and manufacture, to service and disposal.",
    "Programming": "The process of designing and building an executable computer program to accomplish a specific computing result or to perform a specific task.",
    "Real-time Computing": "Computing systems that respond to input within a specific time period.",
    "Software": "Programs and other operating information used by a computer.",
    "Software Engineering": "The application of engineering to the development of software in a systematic method.",
    "Unsolved Problems in Computer Science": "Ongoing challenges and research questions within the field of computer science.",
    "Avionics": "Electronic systems used on aircraft, artificial satellites, and spacecraft.",
    "Circuits": "Physical pathways, typically using wires or printed circuit boards, that carry electrical current.",
    "Connectors": "Electro-mechanical devices used to join electrical terminations and create an electrical circuit.",
    "Consumer Electronics": "Electronic equipment intended for everyday use, typically in private homes.",
    "Digital Electronics": "Electronic circuits that operate using digital signals.",
    "Digital Media": "Digitized content that can be transmitted over the internet or computer networks.",
    "Electrical Components": "Basic electronic elements and their interconnections that are intended to alter the flow of electrical current.",
    "Electronic Design": "The process of creating and developing new electronic equipment.",
    "Electronics Manufacturing": "The industry dedicated to the production of electronic devices and components.",
    "Embedded Systems": "Computer systems with a dedicated function within a larger mechanical or electrical system.",
    "Integrated Circuits": "Electronic circuits with various components such as transistors and resistors, manufactured on a single chip.",
    "Microwave Technology": "The use and application of microwave frequencies for technology and communication.",
    "Molecular Electronics": "The study and application of molecular building blocks for the fabrication of electronic components.",
    "Water Technology": "Technology that is used to treat, manage, and utilize water resources.",
    "Optoelectronics": "Devices that source, detect, and control light, typically considered a sub-field of photonics.",
    "Quantum Electronics": "The study of electronic properties and behavior of materials at quantum level.",
    "Radio-frequency Identification (RFID)": "The use of electromagnetic fields to automatically identify and track tags attached to objects.",
    "Radio Electronics": "The study of electronics that deals with radio waves.",
    "Semiconductors": "Materials that have an electrical conductivity value falling between that of a conductor and an insulator.",
    "Signal Cables": "Wires or cables that are used to transmit electronic signals.",
    "Surveillance": "The monitoring of behavior, activities, or information for the purpose of information gathering, influencing, managing, or directing.",
    "Telecommunications": "The transmission of information by various types of technologies over wire, radio, optical, or other electromagnetic systems.",
    "Aerospace Engineering": "The primary field of engineering concerned with the development of aircraft and spacecraft.",
    "Bioengineering": "The application of the principles of biology and the tools of engineering to create usable, tangible, economically viable products.",
    "Chemical Engineering": "The branch of engineering applying physical sciences (physics and chemistry), life sciences (microbiology and biochemistry), together with applied mathematics and economics to produce, transform, transport, and properly use chemicals, materials, and energy.",
    "Civil Engineering": "A professional engineering discipline that deals with the design, construction, and maintenance of the physical and naturally built environment.",
    "Electrical Engineering": "The branch of engineering that deals with the technology of electricity.",
    "Environmental Engineering": "The branch of engineering that focuses on protecting the environment by reducing waste and pollution.",
    "Materials Science": "An interdisciplinary field applying the properties of matter to various areas of science and engineering.",
    "Mechanical Engineering": "The branch of engineering that involves the design, production, and operation of machinery.",
    "Nuclear Technology": "Technology that involves the reactions of atomic nuclei.",
    "Software Engineering": "The systematic application of engineering approaches to the development of software.",
    "Structural Engineering": "A part of civil engineering where structural engineers are educated to create the 'bones and muscles' that create the form and shape of man-made structures.",
    "Systems Engineering": "An interdisciplinary field of engineering and engineering management that focuses on how to design and manage complex systems over their life cycles.",
    "Transport": "The movement of humans, animals, and goods from one location to another.",
    "By Country": "Refers to the specific technological and applied science practices unique to each country.",
    "Aviation": "The activities surrounding mechanical flight and the aircraft industry.",
    "Cars": "Road vehicles typically with four wheels, powered by an internal combustion engine and able to carry a small number of people.",
    "Cycling": "The use of bicycles for transport, recreation, exercise, or sport.",
    "Public Transport": "Systems of transport for passengers by group travel systems available for use by the general public.",
    "Rail Transport": "The conveyance of passengers and goods by way of wheeled vehicles running on rail tracks.",
    "Road Transport": "The transport of passengers or goods on roads.",
    "Shipping": "The transport of goods by sea or some other means.",
    "Spaceflight": "The process of traveling beyond Earth's atmosphere.",
    "Vehicles": "Machines that transport people or cargo.",
    "Water Transport": "The process of moving people, goods etc. by barge, boat, ship, or sailboat over a sea, ocean, lake, canal, river, etc.",
    "Technology Timelines": "Chronological listings of significant events in the field of technology."
},


"health and fitness":{
    "Self care": "The practice of taking action to preserve or improve one's own health.",
    "Health promotion": "The process of enabling people to increase control over, and to improve, their health.",
    "Life extension": "The study of slowing down or reversing the processes of aging to extend both the maximum and average lifespan.",
    "Prevention": "Measures taken to prevent diseases or injuries rather than curing them or treating their symptoms.",
    "Sexual health": "A state of physical, mental, and social well-being in relation to sexuality.",
    "Sleep": "A naturally recurring state of mind and body characterized by altered consciousness, relatively inhibited sensory activity, reduced muscle activity, and inhibition of nearly all voluntary muscles during rapid eye movement (REM) sleep.",
    "Skin Care": "The range of practices that support skin integrity, enhance its appearance and relieve skin conditions.",
    "Nutrition": "The science that interprets the interaction of nutrients and other substances in food in relation to maintenance, growth, reproduction, health and disease of an organism.",
    "Dietary supplements": "Products intended to supplement the diet that contains one or more dietary ingredients (including vitamins, minerals, herbs or other botanicals, amino acids, and other substances) or their constituents.",
    "Dietetics": "The science of how food and nutrition affects human health.",
    "Nutrients": "Substances needed for growth, metabolism, and for other body functions.",
    "Amino acids": "Organic compounds that combine to form proteins, which are the building blocks of life.",
    "Minerals": "Solid inorganic substances of natural occurrence that are essential to the human body for health.",
    "Nootropics": "Supplements, drugs, or other substances that may improve cognitive function, particularly executive functions, memory, creativity, or motivation, in healthy individuals.",
    "Phytochemicals": "Chemical compounds produced by plants, generally to help them thrive or thwart competitors, predators, or pathogens.",
    "Vitamins": "Organic compounds that an organism needs in small quantities for the proper functioning of its metabolism, essential for the normal growth and development of a multicellular organism.",
    "Nutritional advice pyramids": "Visual diagrams providing guidelines on how to eat healthily.",
    "Exercise": "Any bodily activity that enhances or maintains physical fitness and overall health and wellness.",
    "Aerobics": "A form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines.",
    "Bodyweight exercise": "Strength training exercises that use the individual's own weight to provide resistance against gravity.",
    "Calisthenics": "A form of exercise consisting of a variety of movements which exercise large muscle groups.",
    "Cycling": "The use of bicycles for transport, recreation, exercise, or sport.",
    "Exercise equipment": "Any apparatus or device used during physical activity to enhance the strength or conditioning effects of that exercise.",
    "Exercise instructors": "Professionals who lead, instruct, and motivate individuals or groups in exercise activities.",
    "Dancing": "The art of performing purposefully selected sequences of human movement.",
    "Exercise physiology": "The study of the acute responses and chronic adaptations to a wide range of physical exercise conditions.",
    "Hiking": "A long, vigorous walk, usually on trails or footpaths in the countryside.",
    "Pilates": "A physical fitness system developed in the early 20th century by Joseph Pilates.",
    "Running": "The act of running; moving rapidly on foot.",
    "Sports": "All forms of competitive physical activity which, through casual or organized participation, aim to use, maintain, or improve physical ability and skills.",
    "Swimming": "The self-propulsion of a person through water, usually for recreation, sport, exercise, or survival.",
    "Tai chi": "An internal Chinese martial art practiced for both its defense training, its health benefits, and meditation.",
    "Walking": "The act of traveling or moving from one place to another on foot at a moderate pace.",
    "Weight training exercises": "A common type of strength training for developing the strength and size of skeletal muscles.",
    "Yoga": "A group of physical, mental, and spiritual practices or disciplines which originated in ancient India.",
    "Hygiene": "Conditions or practices conducive to maintaining health and preventing disease, especially through cleanliness.",
    "Cleaning": "The process of removing unwanted substances, such as dirt, infectious agents, and other impurities, from an environment or object.",
    "Oral hygiene": "The practice of keeping one's mouth clean and free of disease and other problems by regular brushing and cleaning between the teeth.",
    "Psychology": "The scientific study of mind and behavior.",
    "Mental health": "A level of psychological well-being, or an absence of mental illness.",
    "Psychotherapy": "The use of psychological methods, particularly when based on regular personal interaction, to help a person change behavior and overcome problems in desired ways.",
    "Public health": "The science and art of preventing disease, prolonging life, and promoting human health through organized efforts and informed choices of society, organizations, public and private communities, and individuals.",
    "Health by country": "The specific health issues, environments, and solutions that are unique to specific countries.",
    "Healthcare": "The maintenance or improvement of health via the prevention, diagnosis, treatment, recovery, or cure of disease, illness, injury, and other physical and mental impairments in people.",
    "Health law": "The legal issues involving health, health care laws, and the health care industry.",
    "Health standards": "The generally accepted norms of quality and performance in healthcare and health maintenance.",
    "Hospitals": "Institutions providing medical and surgical treatment and nursing care for sick or injured people.",
    "Occupational safety and health": "A multidisciplinary field concerned with the safety, health, and welfare of people at work.",
    "Pharmaceutical industry": "The part of the healthcare sector that deals with medications, their development, production, and marketing.",
    "Pharmaceuticals policy": "Policies concerning the development, provision, and use of medications within a health care system.",
    "Safety": "The condition of being protected from or unlikely to cause danger, risk, or injury.",
    "Health science": "The applied science dealing with health, including the study of medicine, nutrition, and other health-related topics.",
    "Clinical research": "A branch of healthcare science that determines the safety and effectiveness of medications, devices, diagnostic products, and treatment regimens intended for human use.",
    "Diseases": "Disorders or malfunctions of the body or mind causing adverse symptoms and health effects.",
    "Epidemiology": "The study and analysis of the distribution, patterns, and determinants of health and disease conditions in defined populations.",
    "Midwifery": "The health science and the health profession that deals with pregnancy, childbirth, and the postpartum period (including care of the newborn).",
    "Nursing": "The profession within the health care sector focused on the care of individuals, families, and communities so they may attain, maintain, or recover optimal health and quality of life.",
    "Nutrition": "The science that interprets the interaction of nutrients and other substances in food in relation to maintenance, growth, reproduction, health, and disease of an organism.",
    "Optometry": "The practice or profession of examining the eyes for visual defects and prescribing corrective lenses.",
    "Pharmacy": "The science and technique of preparing, dispensing, and reviewing drugs and providing additional clinical services.",
    "Public health": "The science and art of preventing disease, prolonging life, and promoting health through organized efforts of society.",
    "Medicine": "The science of diagnosing, treating, or preventing disease and other damage to the body or mind.",
    "Human medicine": "The medical science specifically related to the study and treatment of human health conditions.",
    "Alternative medicine": "A range of medical therapies that are not regarded as orthodox by the medical profession, such as herbalism, homeopathy, and acupuncture.",
    "Cardiology": "The study and treatment of disorders of the heart and the blood vessels.",
    "Endocrinology": "The branch of physiology and medicine concerned with endocrine glands and hormones.",
    "Forensic science": "The application of scientific knowledge to legal problems, especially in relation to the collection, examination, and analysis of physical evidence.",
    "Gastroenterology": "The branch of medicine focused on the digestive system and its disorders.",
    "Human Genetics": "The study of inheritance as it occurs in human beings.",
    "Geriatrics": "The branch of medicine or social science dealing with the health and care of old people.",
    "Gerontology": "The study of the social, cultural, psychological, cognitive, and biological aspects of aging.",
    "Gynecology": "The medical practice dealing with the health of the female reproductive systems (vagina, uterus, and ovaries) and the breasts.",
    "Hematology": "The branch of medicine concerned with the study of the cause, prognosis, treatment, and prevention of diseases related to blood.",
    "Nephrology": "The medical specialty which focuses on kidney conditions and abnormalities.",
    "Neurology": "The branch of medicine dealing with disorders of the nervous system.",
    "Obstetrics": "The field of study concentrated on pregnancy, childbirth, and the postpartum period.",
    "Oncology": "The study and treatment of tumors (cancer).",
    "Ophthalmology": "The branch of medicine and surgery which deals with the diagnosis and treatment of eye disorders.",
    "Orthopedic surgical procedures": "Surgeries that involve the musculoskeletal system.",
    "Pathology": "The study of the causes and effects of disease or injury.",
    "Pediatrics": "The branch of medicine that involves the medical care of infants, children, and adolescents.",
    "Psychiatry": "The medical specialty devoted to the diagnosis, prevention, study, and treatment of mental disorders.",
    "Rheumatology": "The study of rheumatism, arthritis, and other disorders of the joints, muscles, and ligaments.",
    "Surgery": "The branch of medicine that employs operations in the treatment of disease or injury.",
    "Urology": "The branch of medicine that focuses on surgical and medical diseases of the male and female urinary-tract system and the male reproductive organs.",
    "Dentistry": "The branch of medicine that consists of the study, diagnosis, prevention, and treatment of diseases, disorders, and conditions of the oral cavity.",
    "Dental hygiene": "The practice of keeping the mouth, teeth, and gums clean and healthy to prevent disease.",
    "Orthodontics": "A specialty of dentistry that deals with the diagnosis, prevention, and correction of malpositioned teeth and jaws.",
    "Veterinary medicine": "The branch of medicine that deals with the prevention, diagnosis, and treatment of disease, disorder, and injury in animals."
}

}